name: Linter
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          check-latest: true
          go-version: '1.19'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
